<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <DebugType>embedded</DebugType>

        <VersionPrefix>1.0.0</VersionPrefix>
        <VersionSuffix>dev</VersionSuffix>
        <RootNamespace>MoreColors</RootNamespace>
        <Description>Small  Town Of Us Mira Mod that adds new Colors.</Description>
        <!-- <Authors>Nolixo</Authors> -->
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.*"/>
    </ItemGroup>

    <Import Project="../AmongUs.props"/>

    <Target Name="Copy" AfterTargets="Build" Condition="'$(AmongUs)' != ''">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AmongUs)/BepInEx/plugins/" UseSymboliclinksIfPossible="true" />
    </Target>
</Project>
